SilverSolutions1151/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SilverSolutions1151.Data;
using SilverSolutions1151.Data.Entity;
using SilverSolutions1151.Middleware.Extensions;
using SilverSolutions1151.Middleware.Services;
using SilverSolutions1151.Middleware.Services.Interfaces;
using SilverSolutions1151.Migrations;
using SilverSolutions1151.Models;
using SilverSolutions1151.Models.Entity;
using System.Diagnostics;
using System.Web.Http.ModelBinding;

namespace SilverSolutions1151.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly IRawTobaccoService _rawtobaccoService;
        private readonly ITobaccoMixingService _tabaccoMixingService;
        private readonly IReadyStockService _readyStockService;
        private readonly ISoldStockService _soldstockService;
        private bool _isValidate;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context,
            IRawTobaccoService rawTobaccoService, ITobaccoMixingService tabaccoMixingService, 
            IReadyStockService readyStockService, ISoldStockService soldstockService, IConfiguration config)
        {
            _logger = logger;
            _context = context;
            _rawtobaccoService = rawTobaccoService;
            _tabaccoMixingService = tabaccoMixingService;
            _readyStockService = readyStockService;
            _soldstockService = soldstockService;
            _isValidate = config.GetValue<bool>("ValidateStage:IsValidate");
        }
        [AllowAnonymous]
        public IActionResult Index(DateTime? SearchDate)
        {
            ProductionReport productReport = new ProductionReport();
            DateTime filterDate = DateTime.Now;
            if (SearchDate != null)
            {
                filterDate = (DateTime)SearchDate;
            }
            productReport.SearchDate = filterDate;

            // Set the ViewBag property
            ViewBag.FilterDate = filterDate.ToString("yyyy-MM-dd");

            // Retrieve the data for the report
            productReport.RawTobaccoBalanceCurrentDay = _rawtobaccoService.GetRawTobaccoByDate(filterDate);
            productReport.RawTobaccoBalancePreviousDay = _rawtobaccoService.GetRawTobaccoByDate(filterDate.AddDays(-1));
            //Mixed
            productReport.MixedTobaccoBalanceCurrentDay = _tabaccoMixingService.GetMixedTobaccoByDate(filterDate);
            productReport.MixedTobaccoBalancePreviousDay = _tabaccoMixingService.GetMixedTobaccoByDate(filterDate.AddDays(-1));

            //Ready Stock
            var readyStock = _readyStockService.GetReadyStockByDate(filterDate);
            var readyStockpreviousDay = _readyStockService.GetReadyStockByDate(filterDate.AddDays(-1));
            var balancesByPackagingSize = readyStock.GroupBy(b => (int)b.PackagingSize);
            var previousDayBalance = readyStockpreviousDay.GroupBy(b => b.PackagingSize);

            var balanceObjectsByPackagingSize = balancesByPackagingSize.Select(group => new Balance
            {
                PackagingSize = group.Key,
                Amount = group.Sum(b => (int)b.Quantity)
            });


            productReport.BalancesByPackagingSize = balanceObjectsByPackagingSize.ToList();


            //Sold 
            var soldStock = _soldstockService.GetSoldStockBalance(filterDate);
            var soldStockkpreviousDay = _soldstockService.GetSoldStockBalance(filterDate.AddDays(-1));
            var soldStockByPackagingSize = soldStock.GroupBy(b => (int)b.PackagingSize);
            var soldStockPreviousBalance = soldStockkpreviousDay.GroupBy(b => b.PackagingSize);

            var soldStockBalance = soldStockByPackagingSize.Select(group => new Balance
            {
                PackagingSize = group.Key,
                Amount = group.Sum(b => (int)b.Quantity)
            });


            productReport.SoldBySize = soldStockBalance.ToList();

            // Retrieve the errors from TempData
            

            var messages = TempData["ProductionReportErrors"];
               

                       // Convert the error messages back to ModelErrors
            if (messages != null)
            {
                List<string> errorMessageList = ((string[])messages).ToList();
                foreach (var errorMessage in errorMessageList)
                {
                    ModelState.AddModelError("", errorMessage);
                }
            }

            return View(productReport);
        }



        public IActionResult AddTobacco(decimal? quantity,DateTime? manufacturedate)
        {
            // Update the database with the new opening balance
            if (quantity <= 0 && manufacturedate == null) 
            {
                ModelState.AddModelError("Validation", "Quantity and manufacture date are required.");
                var errorMessages = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
                TempData["ProductionReportErrors"] = errorMessages;
                return RedirectToAction("Index", "Home");
            }
            _rawtobaccoService.AddRawTobacco((decimal)quantity, (DateTime)manufacturedate);

            

            // Return the view 
            return RedirectToAction("Index", "Home");
        }

        public IActionResult AddManufacturing(decimal? manufacturingQty, DateTime? manufacturedate,decimal? glycerineQty, decimal? flavourQty
            , decimal? syrupQty, decimal? preservativeQty)
        {

            if (manufacturingQty == null || manufacturingQty <= 0 || manufacturedate == null)
            {
                ModelState.AddModelError("Validation", "Manufacturing Quantity and Manufacture date are required.");
                var errorMessages = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
                TempData["ProductionReportErrors"] = errorMessages;
                return RedirectToAction("Index", "Home");
            }

            if (_isValidate)
            {
                DateTime searchDate = (DateTime)manufacturedate;

                var totalRawTobacco = _rawtobaccoService.GetRawTobaccoByDate(searchDate.EndOfDay());
                if (totalRawTobacco <= manufacturingQty)
                {
                    _logger.LogError($"Tobacco amount exceeds total tobacco in Raw Tobacco.Requested: {manufacturingQty} Total tobacco available:{totalRawTobacco}");
                    ModelState.AddModelError("Quantity", $"Tobacco amount exceeds total tobacco in Raw Tobacco.Requested: {manufacturingQty} Total tobacco available:{totalRawTobacco}.Add additional Raw tobacco or decrease quantity.");
                    var errorMessages = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
                    TempData["ProductionReportErrors"] = errorMessages;
                    return RedirectToAction("Index", "Home");
                }
            }
            // Update the database with the new opening balance
            _tabaccoMixingService.AddTobaccoMixing((decimal)manufacturingQty, (DateTime)manufacturedate, glycerineQty, flavourQty, syrupQty, preservativeQty);
            
               
            // Return the view 
            return RedirectToAction("Index", "Home");
        }

        public IActionResult AddPackaging(decimal? molasesQty, DateTime? packagingDate, decimal? packagingSize)
        {
            if (molasesQty == null || molasesQty <= 0 || packagingDate == null || packagingSize == null || packagingSize <=0)
            {
                ModelState.AddModelError("Validation", "Molases Quantity,Packaging Size and Packaging date are required.");
                var errorMessages = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
                TempData["ProductionReportErrors"] = errorMessages;
                return RedirectToAction("Index", "Home");
            }

            if(_isValidate)
            {
                DateTime searchDate = (DateTime)packagingDate;
                var totalMolases = _tabaccoMixingService.GetMixedTobaccoByDate(searchDate.EndOfDay());
                if(totalMolases < molasesQty)
                {
                    _logger.LogError($"Molases quantity requested {molasesQty} exceeds total molases in Mixed Tobacco {totalMolases}.");
                    ModelState.AddModelError("Quantity", $"Molases qunatity requested {molasesQty} exceeds total molases available in Mixed Tobacco {totalMolases}.Add additional Molases or decrease quantity requested.");
                    var errorMessages = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
                    TempData["ProductionReportErrors"] = errorMessages;
                    return RedirectToAction("Index", "Home");
                }
            }
            // Update the database with the new opening balance
            _readyStockService.AddReadyStock((decimal)molasesQty, (DateTime)packagingDate, (int)packagingSize);

            // Return the view 
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SilverSolutions1151/Controllers/ManufactureController.cs
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SilverSolutions1151.Data;
using SilverSolutions1151.Data.Entity;
using SilverSolutions1151.Models.Entity;
using SilverSolutions1151.Models.Paganation;
using SilverSolutions1151.Repository.Interfaces;
using X.PagedList;

namespace SilverSolutions1151.Controllers
{
    [Authorize]
    public class ManufactureController : Controller
    {
        private readonly IManufactureRepository _manufactureRepository;

        public ManufactureController(IManufactureRepository manufactureRepository)
        {
            _manufactureRepository = manufactureRepository;
        }

        // GET: ManufacturingStage
        public async Task<IActionResult> Index(string stage,
            DateTime? fromDate,
            DateTime? fromDateFilter,
            DateTime? toDateFilter,
            DateTime? toDate,
            int? pageNumber, string currentFilter)
        {
            if (fromDate != null && toDate != null || !String.IsNullOrEmpty(stage))
            {
                pageNumber = 1;
                if (String.IsNullOrEmpty(stage))
                    stage = TempData["stage"]?.ToString() ?? string.Empty;
                else
                    TempData["stage"] = stage;
            }
            else
            {
                fromDate = fromDateFilter;
                toDate = toDateFilter;
                stage = currentFilter;
            }


            TempData["CurrentFilter"] = stage;
            TempData["fromDateFilter"] = fromDate;
            TempData["toDateFilter"] = toDate;
            var manufacturing = new List<Manufacture>();
            if (stage == "MixingTotal")
                stage = "Mixing";
            if (Enum.TryParse(typeof(Models.Entity.ProductionStage),stage,out var result))
            {
                manufacturing = _manufactureRepository.GetManufactureItemsByDateAndType((Models.Entity.ProductionStage)result, fromDate, toDate);
            }
            
            
            
            var viewmodel = await PaginatedList<Manufacture>.CreateAsync(manufacturing.AsQueryable().AsNoTracking(), pageNumber ?? 1, 20);
     
            return View("Index", viewmodel);
        }

        public async Task<IActionResult> Mixing(string stage,
           DateTime? fromDate,
           DateTime? fromDateFilter,
           DateTime? toDateFilter,
           DateTime? toDate,
           int? pageNumber, string currentFilter)
        {
            if (fromDate != null && toDate != null || !String.IsNullOrEmpty(stage))
            {
                pageNumber = 1;
                if (String.IsNullOrEmpty(stage))
                    stage = TempData["stage"].ToString();
                else
                    TempData["stage"] = stage;
            }
            else
            {
                fromDate = fromDateFilter;
                toDate = toDateFilter;
                stage = currentFilter;
            }


            TempData["CurrentFilter"] = stage;
            TempData["fromDateFilter"] = fromDate;
            TempData["toDateFilter"] = toDate;
            var manufacturing = new List<Manufacture>();
            if (Enum.TryParse(typeof(Models.Entity.ProductionStage), stage, out var result))
            {
                manufacturing = _manufactureRepository.GetManufactureItemsByDateAndType((Models.Entity.ProductionStage)result, fromDate, toDate);
            }


            var viewmodel = await PaginatedList<Manufacture>.CreateAsync(manufacturing.AsQueryable().AsNoTracking(), pageNumber ?? 1, 20);

            return View(viewmodel);
        }

        public async Task<IActionResult> Packaging(string stage,
    DateTime? fromDate,
    DateTime? fromDateFilter,
    DateTime? toDateFilter,
    DateTime? toDate,
    int? pageNumber, string currentFilter)
        {
            // Check if search parameters are provided
            if (fromDate != null && toDate != null || !String.IsNullOrEmpty(stage))
            {
                // Reset page number to 1 and save search parameters to TempData
                pageNumber = 1;
                if (String.IsNullOrEmpty(stage))
                {
                    stage = TempData["stage"]?.ToString();
                }
                else
                {
                    TempData["stage"] = stage;
                }
                
                TempData["fromDateFilter"] = fromDate;
                TempData["toDateFilter"] = toDate;
            }
            else
            {
                // Use previous search parameters from TempData
                stage = TempData["stage"]?.ToString();
                fromDate = fromDateFilter ?? TempData["fromDateFilter"] as DateTime?;
                toDate = toDateFilter ?? TempData["toDateFilter"] as DateTime?;
            }

            // Save current search filter to TempData
            TempData["CurrentFilter"] = stage;

            // Get manufacturing items based on search parameters
            var manufacturing = new List<Manufacture>();
            if (Enum.TryParse(typeof(Models.Entity.ProductionStage), stage, out var result))
            {
                manufacturing = _manufactureRepository.GetManufactureItemsByDateAndType((Models.Entity.ProductionStage)result, fromDate, toDate);
            }

            // Create paginated list of manufacturing items
            var viewmodel = await PaginatedList<Manufacture>.CreateAsync(manufacturing.AsQueryable().AsNoTracking(), pageNumber ?? 1, 20);

            return View("Packaging", viewmodel);

        }




    }
}

SilverSolutions1151/Views/Home/Index.cshtml
@model SilverSolutions1151.Data.Entity.ProductionReport

@{
    ViewData["Title"] = "Home Page";
}

<style type="text/css">
    .search-label-container {
        display: flex;
        align-items: center;
        border: 1px solid #ced4da;
        border-radius: 0.25rem;
        padding: 0.375rem 0.75rem;
    }

    .search-label {
        font-weight: bold;
        margin-right: 0.5rem;
    }

    .control-label-bold {
        font-weight: bold;
    }

    .rounded-border-container {
        border: 1px solid #ced4da;
        border-radius: 0.25rem;
        padding: 1rem;
        margin-top: 1rem;
    }


    .balance-label-container {
        margin-bottom: 1rem;
    }

    .manufacture-date-label {
        margin-right: 0.5rem;
    }

    .rounded-border-heading {
        margin-top: 0;
        margin-bottom: 0.5rem;
    }

    .rounded-border-separator {
        margin-top: 0.5rem;
        margin-bottom: 0.5rem;
    }
</style>

<br />
<br />

<div class="row">
    <div class="col-md-12">
        <div class="search-label-container rounded-container">
            <label for="datePicker" class="search-label">Search manufacture date:</label>
            <input type="date" id="datePicker" class="form-control" value="@Model.SearchDate" />
            <button type="button" class="btn btn-primary" onclick="searchByDate()">Search</button>
        </div>
    </div>
</div>

<br/>

<form asp-action="Create" class="rounded-border-container">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    @if (ViewBag.FilterDate != null)
    {
        <p><strong>Showing balances for : @ViewBag.FilterDate</strong></p>
    }
    <div class="form-group">
        <div class="rounded-border-container">
            <h4 class="rounded-border-heading">Raw Tobacco</h4>
            <hr class="rounded-border-separator">
            <div class="balance-label-container">
                <label class="balance-label">Opening Balance(Kg): @Model.RawTobaccoBalancePreviousDay</label>
                <br />
                <label class="balance-label">Current Balance(Kg): @Model.RawTobaccoBalanceCurrentDay</label>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="OpeningBalance" class="manufacture-date-label">Manufacture Date:</label>
                    <input asp-for="OpeningBalance" class="form-control" type="date" id="ManufactureDate" />
                </div>

                <div class="form-group col-md-6">
                    <label asp-for="OpeningBalance" class="manufacture-date-label">Quantity(Kg):</label>
                    <input asp-for="OpeningBalance" class="form-control" id="quantity"/>
                </div>
            </div>

            <div class="form-group">
                <button type="button" class="btn btn-primary" onclick="addRawTobacco()">Add</button>
                <button type="button" class="btn btn-success" onclick="viewRawTobaccoTransaction()">View</button>
            </div>

        </div>
    </div>


    <div class="form-group">
        <div class="rounded-border-container">
            <h4 class="rounded-border-heading">Manufacturing</h4>
            <hr class="rounded-border-separator">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="OpeningBalance" class="manufacture-date-label">Manufacture Date:</label>
                    <input asp-for="OpeningBalance" class="form-control" type="date" id="manufacturingDate" />
                </div>

                <div class="form-group col-md-6">
                    <label asp-for="OpeningBalance" class="manufacture-date-label">Tobacco Qty(Kg):</label>
                    <input asp-for="OpeningBalance" class="form-control" id="tobaccoQty"/>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="OpeningBalance" class="manufacture-date-label">Syrup Qty(kg):</label>
                    <input asp-for="OpeningBalance" class="form-control" id="SyrupQty" />
                </div>

                <div class="form-group col-md-6">
                    <label asp-for="OpeningBalance" class="manufacture-date-label">Glycerine Qty(Kg):</label>
                    <input asp-for="OpeningBalance" class="form-control" id="GlycerinQty" />
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="OpeningBalance" class="manufacture-date-label">Preservative Qty(Kg):</label>
                    <input asp-for="OpeningBalance" class="form-control" id="PreservativeQty" />
                </div>

                <div class="form-group col-md-6">
                    <label asp-for="OpeningBalance" class="manufacture-date-label">Flavour Qty(Kg):</label>
                    <input asp-for="OpeningBalance" class="form-control" id="FlavourQty" />
                </div>
            </div>

            <div class="form-group">
                <button type="button" class="btn btn-primary" onclick="addManufacturing()">Add</button>
                <button type="button" class="btn btn-success" onclick="viewMixedTobaccoTransaction()">View</button>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="rounded-border-container">
            <h4 class="rounded-border-heading">Tobacco mixing in progress</h4>
            <hr class="rounded-border-separator">
            <div class="balance-label-container">
                <label class="balance-label">Opening Balance(Kg): @Model.MixedTobaccoBalancePreviousDay</label>
                <br />
                <label class="balance-label">Current Balance(Kg): @Model.MixedTobaccoBalanceCurrentDay</label>
            </div>

            <div class="form-group">
                <button type="button" class="btn btn-success" onclick="viewMixedTobaccoTotalTransaction()">View</button>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="rounded-border-container">
            <h4 class="rounded-border-heading">Packaging</h4>
            <hr class="rounded-border-separator">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="OpeningBalance" class="manufacture-date-label">Manufacture Date:</label>
                    <input asp-for="OpeningBalance" class="form-control" type="date" id="PackagingDate" />
                </div>

                <div class="form-group col-md-6">
                    <label asp-for="OpeningBalance" class="manufacture-date-label">Molases Quantity(Kg):</label>
                    <input asp-for="OpeningBalance" class="form-control" id="MolasesQty" />
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="OpeningBalance" class="manufacture-date-label">Packaging Size(g):</label>
                    <input asp-for="OpeningBalance" class="form-control" id="PackagingSize" />
                </div>
            </div>

            <div class="form-group">
                <button type="button" class="btn btn-primary" onclick="addPackaging()">Add</button>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="rounded-border-container">
            <h4 class="rounded-border-heading">Ready Stock</h4>
            <hr class="rounded-border-separator">
            @if (Model.BalancesByPackagingSize.Count == 0)
            {
                <p>No data has been captured for the current day.</p>
            }
            else
            {
                <div class="balance-group-container">
                    @foreach (var group in Model.BalancesByPackagingSize)
                    {
                        <div class="rounded-border-container">
                            <p class="balance-group-amount"><strong>Packaging Size(g): @group.PackagingSize</strong></p>
                            <p class="balance-group-amount">Current Balance(Boxes): @group.Amount</p>
                        </div>
                    }
                </div>
                <br />

                <div class="form-group">
                    <button type="button" class="btn btn-success" onclick="viewReadyStockTransaction()">View</button>
                </div>
            }
        </div>
    </div>


    <div class="form-group">
        <div class="rounded-border-container">
            <h4 class="rounded-border-heading">Sold</h4>
            <hr class="rounded-border-separator">
            <div class="balance-group-container">
                @foreach (var group in Model.SoldBySize)
                {
                    <div class="rounded-border-container">
                        <p class="balance-group-amount"><strong>Packaging Size(g): @group.PackagingSize</strong></p>
                        <p class="balance-group-amount">Current Balance(Boxes): @group.Amount</p>
                    </div>
                }
            </div>
            <br />

            <div class="form-group">
                <a href="@Url.Action("Create", "CustomerInvoices")" class="btn btn-primary ml-2">Create Invoice</a>
                <button type="button" class="btn btn-success" onclick="viewSoldTransaction()">View</button>
                <a href="@Url.Action("Index", "CustomerInvoices")" class="btn btn-primary ml-2">View Invoices</a>
            </div>
        </div>
    </div>
</form>

@section Scripts
    {
    <script type="text/javascript">
        function addRawTobacco() {
            console.log('addRawTobacco function executed.');

            const quantity = document.getElementById("quantity").value;
            const manufactureDate = document.getElementById("ManufactureDate").value;

            const url = '@Url.Action("AddTobacco", "Home")?quantity='+ quantity +'&manufactureDate=' + manufactureDate;
            window.location.href = url;
        }

        function addManufacturing() {
            console.log('addManufacturing function executed.');

            const manufacturingQty = document.getElementById("tobaccoQty").value;
            const glycerineQty = document.getElementById("GlycerinQty").value;
            const flavourQty = document.getElementById("FlavourQty").value;
            const syrupQty = document.getElementById("SyrupQty").value;
            const preservativeQty = document.getElementById("PreservativeQty").value;
            const manufactureDate = document.getElementById("manufacturingDate").value;

            const url = '@Url.Action("AddManufacturing", "Home")?manufacturingQty='+manufacturingQty+'&manufactureDate='+manufactureDate+'&glycerineQty='+glycerineQty+'&flavourQty='+flavourQty+'&syrupQty='+syrupQty+'&preservativeQty='+preservativeQty;
            window.location.href = url;
        }

        function addPackaging() {
            console.log('addPackaging function executed.');
            debugger;
            const MolasesQty = document.getElementById("MolasesQty").value;
            const packagingSize = document.getElementById("PackagingSize").value;
            const packagingDate = document.getElementById("PackagingDate").value;

            const url = '@Url.Action("AddPackaging", "Home")?molasesQty=' + MolasesQty + '&packagingDate=' + packagingDate + '&packagingSize=' + packagingSize;

            window.location.href = url;
        }

        function viewRawTobaccoTransaction() {
            console.log('viewRawTobaccoTransaction function executed.');

            const url = '@Url.Action("Index", "Manufacture")?stage=RawTobacco';
            window.location.href = url;
        }

        function viewMixedTobaccoTransaction() {
            console.log('viewMixedTobaccoTransaction function executed.');

            const url = '@Url.Action("Mixing", "Manufacture")?stage=Mixing';
            window.location.href = url;
        }

        function viewMixedTobaccoTotalTransaction() {
            console.log('viewMixedTobaccoTransaction function executed.');

            const url = '@Url.Action("Index", "Manufacture")?stage=MixingTotal';
            window.location.href = url;
        }

        function viewReadyStockTransaction() {
            console.log('viewReadyStockTransaction function executed.');

            const url = '@Url.Action("Packaging", "Manufacture")?stage=Complete';
            window.location.href = url;
        }

        function viewSoldTransaction() {
            console.log('viewSoldTransaction function executed.');

            const url = '@Url.Action("Index", "Manufacture")?stage=Sold';
            window.location.href = url;
        }

        function searchByDate() {
            console.log('searchByDate function executed.');

            const manufactureDate = document.getElementById("datePicker").value;

            const url = '@Url.Action("Index", "Home")?searchDate='+ manufactureDate;
            window.location.href = url;
        }
    </script>
}